spring:
  application:
    name: accounts-service
  profiles:
    active: prod

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

#  config:
#    import: "optional:configserver:http://localhost:8888/accounts-service/prod"

management:
 endpoints:
   web:
     exposure:
        include: '*'

server:
 port: 8081
