
build:
  version: "2.0.0"

spring:
 config:
   activate:
      on-profile: dev

 accounts:
    version: "2.0.0"
    message: "welcome to the accounts related dev-envi"
    license: "accounts-service@ibank.com"
    url: "https://accounts-service.com"
    contactDetails:
      name: "Pavan- Developer"
      email: "pavan21@gmail.com"
      onCallSupport:
       - "123-456-7890"
       - "pavan21@gmail.com"
