spring:
  application:
    name: cards-service


management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
 port: 8082
build:
  version: "1.0.0"

accounts:
  version: "1.0.0"
  message: "Welcome to the accounts-section"
  contact: "accounts-service@ibank.com"
  license: "accounts-service@ibank.com"
  contactDetails:
    name: "accounts-service"
    url: "https://accounts-service.com"
    email: "accounts-service@ibank.com"
  onCallSupport:
    name: "Pavan-kumar"
    phone: "123-456-7890"
    email: "accounts-service@ibank.com"


