
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8082

build:
  version: "2.0.0"

accounts:
  version: "2.0.0"
  message: "welcome to the accounts related dev-envi"
  license: "accounts-service@ibank.com"
  url: "https://accounts-service.com"
  contactDetails:
    name: "Pavan- Developer"
    email: "pavan21@gmail.com"
    onCallSupport:
      - "123-456-7890"
      - "pavan21@gmail.com"
