
build:
  version: "2.0"


spring:
  config:
    activate:
      on-profile: prod

loans:
  version: "2.0"
  message: "welcome to the loans related prod-envi"
  license: "loans-service@ibank.com"
  url: "https://loans-service.com"
  contactDetails:
    name: "Pavan- Developer"
    email: "pavan21@gmail.com"
    onCallSupport:
      - "123-456-7890"
      - "pavan21@gmail.com"
