spring:
  application:
    name: "loans"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  fetch-registry: true
  instance:
    preferIpAddress: true

#   =========================
#   H2 Database Configuration
#   =========================
  datasource:
    url: jdbc:h2:mem:loansdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console


    config:
      import: "optional:configserver:http://localhost:8888"

    profiles:
        active:
          - "dev"
          - "prod"
          - "qa"

# =========================
# Management / Actuator
# =========================
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

server:
  port: 8083

build:
  version: "3.0"

loans:
  message: "welcome to the cards related local api's"
  contactDetails:
    name: "Ravi - Developer"
    email: "Ravi21@gmail.com"
    onCallSupport:
      - "412-419-3491"
      - "915-382-1932"
